### ISSUE TITLE
Missing code in `app/routes/camera.js`

### ISSUE THREAD

**Issue by chapeljuice** [spencercarli/react-native-snapchat-clone#3]
Noticed this little guy on line 78 of `camera.js`, looks like some code was left out accidentally:
<img width="443" alt="screen shot 2017-06-28 at 3 54 38 pm" src="https://user-images.githubusercontent.com/862642/27664042-406f9c72-5c1a-11e7-9a7e-2d4bf2b2ad84.png">

**Comment by chapeljuice** [comment]
Bah never mind, I'm dumb. Just noticed it was an empty, self-closed tag. Please, move along. Nothing to see here.

**Comment by spencercarli** [comment]
😄
